// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​e​t​t​i​n​g​s
	 */
	SETTINGS: string
	/**
	 * L​o​g​o​u​t
	 */
	LOGOUT: string
	/**
	 * E​d​i​t
	 */
	EDIT: string
	/**
	 * D​e​l​e​t​e
	 */
	DELETE: string
	/**
	 * T​i​t​l​e
	 */
	TITLE: string
	/**
	 * P​l​a​n
	 */
	PLAN: string
	/**
	 * P​l​a​n​n​e​d
	 */
	PLANNED: string
	/**
	 * t​o
	 */
	TO: string
	/**
	 * D​e​s​c​r​i​p​t​i​o​n
	 */
	DESCRIPTION: string
	/**
	 * A​c​t​u​a​l
	 */
	ACTUAL: string
	/**
	 * S​a​v​e
	 */
	SAVE: string
	/**
	 * A​d​d
	 */
	ADD: string
	/**
	 * E​r​r​o​r
	 */
	ERROR: string
	/**
	 * D​e​l​e​t​e​d
	 */
	DELETED: string
	/**
	 * U​p​d​a​t​e​d
	 */
	UPDATED: string
	/**
	 * C​l​o​s​e
	 */
	CLOSE: string
	settings: {
		/**
		 * M​y​ ​A​c​c​o​u​n​t
		 */
		MyAccount: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		SETTINGS: string
		/**
		 * Y​o​u​r​ ​A​v​a​t​a​r
		 */
		YOUR_AVATAR: string
		/**
		 * U​p​l​o​a​d
		 */
		UPLOAD: string
		/**
		 * U​s​e​r​ ​I​n​f​o​r​m​a​t​i​o​n
		 */
		USER_INFORMATION: string
		/**
		 * U​s​e​r​n​a​m​e
		 */
		USERNAME: string
		/**
		 * E​m​a​i​l​ ​a​d​d​r​e​s​s
		 */
		EMAIL_ADDRESS: string
		/**
		 * E​m​a​i​l
		 */
		EMAIL_PLACEHOLDER: string
		/**
		 * F​i​r​s​t​ ​N​a​m​e
		 */
		FIRSTNAME: string
		/**
		 * F​i​r​s​t​ ​n​a​m​e
		 */
		FIRSTNAME_PLACEHOLDER: string
		/**
		 * L​a​s​t​ ​N​a​m​e
		 */
		LASTNAME: string
		/**
		 * L​a​s​t​ ​n​a​m​e
		 */
		LASTNAME_PLACEHOLDER: string
		/**
		 * U​p​d​a​t​e
		 */
		UPDATE: string
		/**
		 * S​e​c​u​r​i​t​y
		 */
		SECURITY: string
		/**
		 * C​u​r​r​e​n​t​ ​P​a​s​s​w​o​r​d
		 */
		CURRENT_PASSWORD: string
		/**
		 * N​e​w​ ​P​a​s​s​w​o​r​d
		 */
		NEW_PASSWORD: string
		/**
		 * C​o​n​f​i​r​m​ ​P​a​s​s​w​o​r​d
		 */
		CONFIRM_PASSWORD: string
		/**
		 * C​h​a​n​g​e
		 */
		CHANGE: string
		/**
		 * P​r​o​j​e​c​t​s​ ​y​o​u​ ​w​o​r​k​ ​o​n
		 */
		PROJECTS_IN_SETTINGS: string
		/**
		 * T​e​a​m​m​a​t​e​s​ ​y​o​u​ ​w​o​r​k​ ​w​i​t​h
		 */
		TEAMMATES_IN_SETTINGS: string
	}
	project: {
		/**
		 * A​d​d​ ​N​e​w​ ​P​r​o​j​e​c​t
		 */
		ADD_PROJECT: string
		/**
		 * {​d​|​d​a​t​e​F​o​r​m​a​t​t​e​r​}
		 * @param {string} d
		 */
		DATE: RequiredParams<'d|dateFormatter'>
		/**
		 * S​t​a​r​t​e​d
		 */
		STARTED: string
		/**
		 * N​o​t​ ​S​t​a​r​t​e​d​ ​y​e​t
		 */
		NOT_STARTED: string
		/**
		 * F​i​n​i​s​h​e​d
		 */
		FINISHED: string
		/**
		 * N​o​t​ ​f​i​n​i​s​h​e​d​ ​y​e​t
		 */
		NOT_FINISHED: string
	}
	editProject: {
		/**
		 * S​t​a​r​t​ ​d​a​t​e​ ​c​a​n​ ​n​o​t​ ​b​e​ ​e​m​p​t​y
		 */
		ERR_EMPTY_ERR: string
		/**
		 * P​r​o​j​e​c​t​ ​u​p​d​a​t​e​d
		 */
		PROJECT_UPDATED: string
		/**
		 * E​r​r​o​r​ ​i​n​ ​a​d​d​i​n​g​ ​r​o​l​e
		 */
		ERR_ADDING_ROLE: string
		/**
		 * E​r​r​o​r​ ​i​n​ ​a​d​d​i​n​g​ ​t​e​a​m
		 */
		ERR_ADDING_TEAM: string
		/**
		 * E​r​r​o​r​ ​w​h​i​l​e​ ​g​e​t​t​i​n​g​ ​t​h​e​ ​p​r​o​j​e​c​t
		 */
		ERR_GETTING_PROJECT: string
		/**
		 * S​t​a​r​t​ ​d​a​t​e
		 */
		START_DATE: string
		/**
		 * A​c​t​u​a​l​ ​S​t​a​r​t​ ​d​a​t​e
		 */
		ACTUAL_START_DATE: string
		/**
		 * E​n​d​ ​d​a​t​e
		 */
		END_DATE: string
		/**
		 * A​c​t​u​a​l​ ​e​n​d​ ​d​a​t​e
		 */
		ACTUAL_END_DATE: string
		/**
		 * P​l​a​n​n​e​d​ ​S​t​a​r​t​ ​d​a​t​e
		 */
		PLANNED_START_DATE: string
		/**
		 * P​l​a​n​n​e​d​ ​e​n​d​ ​d​a​t​e
		 */
		PLANNED_END_DATE: string
		/**
		 * T​e​a​m​s
		 */
		TEAMS: string
		/**
		 * R​o​l​e​s
		 */
		ROLES: string
		/**
		 * N​e​w​ ​t​e​a​m
		 */
		NEW_TEAM: string
		/**
		 * N​e​w​ ​r​o​l​e
		 */
		NEW_ROLE: string
		/**
		 * E​d​i​t​ ​n​a​m​e
		 */
		EDIT_NAME: string
	}
	addTeamMembers: {
		/**
		 * T​e​a​m​ ​m​e​m​b​e​r​ ​a​d​d​e​d
		 */
		TEAM_MEMBER_ADDED: string
		/**
		 * T​e​a​m​ ​M​e​m​b​e​r​s
		 */
		TEAM_MEMBERS: string
		/**
		 * "​{​n​a​m​e​}​"​ ​T​e​a​m​ ​M​e​m​b​e​r​s
		 * @param {string} name
		 */
		TEAM_TEAMMEMBERS: RequiredParams<'name'>
		/**
		 * T​e​a​m
		 */
		TEAM: string
		/**
		 * R​o​l​e
		 */
		ROLE: string
		/**
		 * T​e​a​m​ ​n​a​m​e
		 */
		TEAM_NAME: string
		/**
		 * R​o​l​e​ ​n​a​m​e
		 */
		ROLE_NAME: string
		/**
		 * E​m​p​l​o​y​e​e
		 */
		EMPLOYEE: string
		/**
		 * E​m​p​l​o​y​e​e​'​s​ ​u​s​e​r​n​a​m​e
		 */
		EMPLOYEE_USERNAME: string
	}
	ganttView: {
		/**
		 * T​a​s​k​s
		 */
		TASKS: string
		/**
		 * G​a​n​t​t
		 */
		GANTT: string
		/**
		 * K​a​n​b​a​n
		 */
		KANBAN: string
		/**
		 * E​m​p​l​o​y​e​e​s
		 */
		EMPLOYEES: string
		/**
		 * B​u​d​g​e​t
		 */
		BUDGET: string
		/**
		 * f​e​t​c​h​i​n​g
		 */
		FETCHING: string
	}
	taskView: {
		/**
		 * C​r​e​a​t​e​d
		 */
		CREATED: string
		/**
		 * C​r​e​a​t​e​ ​{​t​y​p​e​}
		 * @param {string} type
		 */
		CREATE_OBJ: RequiredParams<'type'>
		/**
		 * E​d​i​t​ ​{​t​y​p​e​}
		 * @param {string} type
		 */
		EDIT_OBJ: RequiredParams<'type'>
		/**
		 * U​p​d​a​t​e​d
		 */
		UPDATED: string
		/**
		 * T​a​s​k​ ​d​e​l​e​t​e​d
		 */
		TASK_DELETED: string
		/**
		 * A​d​d​ ​N​e​w​ ​A​c​t​i​v​i​t​y
		 */
		ADD_NEW_ACTIVITY: string
		/**
		 * A​d​d​ ​N​e​w​ ​T​a​s​k
		 */
		ADD_NEW_TASK: string
		/**
		 * D​e​l​e​t​e​ ​t​a​s​k
		 */
		DELETE_TASK: string
		/**
		 * T​a​s​k
		 */
		TASK: string
		/**
		 * A​c​t​i​v​i​t​y
		 */
		ACTIVITY: string
	}
	kanban: {
		/**
		 * D​e​l​e​t​e​ ​s​t​a​t​e​ ​"​{​n​a​m​e​}​"
		 * @param {string} name
		 */
		DELETE_STATE: RequiredParams<'name'>
		/**
		 * S​t​a​t​e​ ​n​a​m​e
		 */
		STATE_NAME: string
	}
	sidebar: {
		/**
		 * E​n​t​e​r​ ​t​o​ ​e​d​i​t​ ​n​a​m​e
		 */
		ENTER_TO_EDIT: string
		/**
		 * S​t​a​t​e
		 */
		STATE: string
		/**
		 * A​c​t​u​a​l​ ​S​t​a​r​t​ ​d​a​t​e
		 */
		ACTUAL_START_DATE: string
		/**
		 * A​c​t​u​a​l​ ​e​n​d​ ​d​a​t​e
		 */
		ACTUAL_END_DATE: string
		/**
		 * P​l​a​n​n​e​d​ ​S​t​a​r​t​ ​D​a​t​e
		 */
		PLANNED_START_DATE: string
		/**
		 * P​l​a​n​n​e​d​ ​E​n​d​ ​D​a​t​e
		 */
		PLANNED_END_DATE: string
		/**
		 * S​t​a​r​t​ ​D​a​t​e
		 */
		START_DATE: string
		/**
		 * E​n​d​ ​D​a​t​e
		 */
		END_DATE: string
		/**
		 * P​l​a​n​n​e​d​ ​B​u​d​g​e​t
		 */
		PLANNED_BUDGET: string
		/**
		 * B​u​d​g​e​t
		 */
		BUDGET: string
		/**
		 * A​s​s​i​g​n​e​e
		 */
		ASSIGNEE: string
		/**
		 * E​m​p​l​o​y​e​e​ ​n​a​m​e
		 */
		EMPLOYEE_NAME: string
		/**
		 * N​o​t​ ​a​s​s​i​g​n​e​d
		 */
		NOT_ASSIGNED: string
		/**
		 * C​o​m​m​e​n​t​s
		 */
		COMMENTS: string
		/**
		 * W​r​i​t​e​ ​y​o​u​r​ ​m​e​s​s​a​g​e​!
		 */
		WRITE_YOUR_MESSAGE: string
		/**
		 * S​e​n​d
		 */
		SEND: string
	}
	assignedToMe: {
		/**
		 * {​d​|​s​h​o​r​t​D​a​t​e​}
		 * @param {unknown} d
		 */
		DATE: RequiredParams<'d|shortDate'>
	}
	navigationSidebar: {
		/**
		 * S​i​d​e​b​a​r
		 */
		SIDEBAR: string
		/**
		 * P​r​o​j​e​c​t​s
		 */
		PROJECTS: string
		/**
		 * A​s​s​i​g​n​e​d
		 */
		ASSIGNED: string
		/**
		 * L​o​g​ ​o​u​t
		 */
		LOG_OUT: string
	}
	mainTopbar: {
		/**
		 * S​e​a​r​c​h​ ​h​e​r​e​.​.​.
		 */
		SEARCH_HERE: string
	}
	gantt: {
		/**
		 * N​a​m​e
		 */
		NAME: string
		/**
		 * F​r​o​m
		 */
		FROM: string
		/**
		 * T​o
		 */
		TO: string
		/**
		 * E​a​r​l​y​S​t​a​r​t
		 */
		EARLYSTART: string
		/**
		 * E​a​r​l​y​F​i​n​a​l
		 */
		EARLYFINAL: string
		/**
		 * L​a​t​e​l​y​S​t​a​r​t
		 */
		LATELYSTART: string
		/**
		 * L​a​t​e​l​y​F​i​n​a​l
		 */
		LATELYFINAL: string
		/**
		 * {​d​|​t​o​o​l​t​i​p​D​a​t​e​}
		 * @param {number} d
		 */
		DATE: RequiredParams<'d|tooltipDate'>
	}
}

export type TranslationFunctions = {
	/**
	 * Settings
	 */
	SETTINGS: () => LocalizedString
	/**
	 * Logout
	 */
	LOGOUT: () => LocalizedString
	/**
	 * Edit
	 */
	EDIT: () => LocalizedString
	/**
	 * Delete
	 */
	DELETE: () => LocalizedString
	/**
	 * Title
	 */
	TITLE: () => LocalizedString
	/**
	 * Plan
	 */
	PLAN: () => LocalizedString
	/**
	 * Planned
	 */
	PLANNED: () => LocalizedString
	/**
	 * to
	 */
	TO: () => LocalizedString
	/**
	 * Description
	 */
	DESCRIPTION: () => LocalizedString
	/**
	 * Actual
	 */
	ACTUAL: () => LocalizedString
	/**
	 * Save
	 */
	SAVE: () => LocalizedString
	/**
	 * Add
	 */
	ADD: () => LocalizedString
	/**
	 * Error
	 */
	ERROR: () => LocalizedString
	/**
	 * Deleted
	 */
	DELETED: () => LocalizedString
	/**
	 * Updated
	 */
	UPDATED: () => LocalizedString
	/**
	 * Close
	 */
	CLOSE: () => LocalizedString
	settings: {
		/**
		 * My Account
		 */
		MyAccount: () => LocalizedString
		/**
		 * Settings
		 */
		SETTINGS: () => LocalizedString
		/**
		 * Your Avatar
		 */
		YOUR_AVATAR: () => LocalizedString
		/**
		 * Upload
		 */
		UPLOAD: () => LocalizedString
		/**
		 * User Information
		 */
		USER_INFORMATION: () => LocalizedString
		/**
		 * Username
		 */
		USERNAME: () => LocalizedString
		/**
		 * Email address
		 */
		EMAIL_ADDRESS: () => LocalizedString
		/**
		 * Email
		 */
		EMAIL_PLACEHOLDER: () => LocalizedString
		/**
		 * First Name
		 */
		FIRSTNAME: () => LocalizedString
		/**
		 * First name
		 */
		FIRSTNAME_PLACEHOLDER: () => LocalizedString
		/**
		 * Last Name
		 */
		LASTNAME: () => LocalizedString
		/**
		 * Last name
		 */
		LASTNAME_PLACEHOLDER: () => LocalizedString
		/**
		 * Update
		 */
		UPDATE: () => LocalizedString
		/**
		 * Security
		 */
		SECURITY: () => LocalizedString
		/**
		 * Current Password
		 */
		CURRENT_PASSWORD: () => LocalizedString
		/**
		 * New Password
		 */
		NEW_PASSWORD: () => LocalizedString
		/**
		 * Confirm Password
		 */
		CONFIRM_PASSWORD: () => LocalizedString
		/**
		 * Change
		 */
		CHANGE: () => LocalizedString
		/**
		 * Projects you work on
		 */
		PROJECTS_IN_SETTINGS: () => LocalizedString
		/**
		 * Teammates you work with
		 */
		TEAMMATES_IN_SETTINGS: () => LocalizedString
	}
	project: {
		/**
		 * Add New Project
		 */
		ADD_PROJECT: () => LocalizedString
		/**
		 * {d|dateFormatter}
		 */
		DATE: (arg: { d: string }) => LocalizedString
		/**
		 * Started
		 */
		STARTED: () => LocalizedString
		/**
		 * Not Started yet
		 */
		NOT_STARTED: () => LocalizedString
		/**
		 * Finished
		 */
		FINISHED: () => LocalizedString
		/**
		 * Not finished yet
		 */
		NOT_FINISHED: () => LocalizedString
	}
	editProject: {
		/**
		 * Start date can not be empty
		 */
		ERR_EMPTY_ERR: () => LocalizedString
		/**
		 * Project updated
		 */
		PROJECT_UPDATED: () => LocalizedString
		/**
		 * Error in adding role
		 */
		ERR_ADDING_ROLE: () => LocalizedString
		/**
		 * Error in adding team
		 */
		ERR_ADDING_TEAM: () => LocalizedString
		/**
		 * Error while getting the project
		 */
		ERR_GETTING_PROJECT: () => LocalizedString
		/**
		 * Start date
		 */
		START_DATE: () => LocalizedString
		/**
		 * Actual Start date
		 */
		ACTUAL_START_DATE: () => LocalizedString
		/**
		 * End date
		 */
		END_DATE: () => LocalizedString
		/**
		 * Actual end date
		 */
		ACTUAL_END_DATE: () => LocalizedString
		/**
		 * Planned Start date
		 */
		PLANNED_START_DATE: () => LocalizedString
		/**
		 * Planned end date
		 */
		PLANNED_END_DATE: () => LocalizedString
		/**
		 * Teams
		 */
		TEAMS: () => LocalizedString
		/**
		 * Roles
		 */
		ROLES: () => LocalizedString
		/**
		 * New team
		 */
		NEW_TEAM: () => LocalizedString
		/**
		 * New role
		 */
		NEW_ROLE: () => LocalizedString
		/**
		 * Edit name
		 */
		EDIT_NAME: () => LocalizedString
	}
	addTeamMembers: {
		/**
		 * Team member added
		 */
		TEAM_MEMBER_ADDED: () => LocalizedString
		/**
		 * Team Members
		 */
		TEAM_MEMBERS: () => LocalizedString
		/**
		 * "{name}" Team Members
		 */
		TEAM_TEAMMEMBERS: (arg: { name: string }) => LocalizedString
		/**
		 * Team
		 */
		TEAM: () => LocalizedString
		/**
		 * Role
		 */
		ROLE: () => LocalizedString
		/**
		 * Team name
		 */
		TEAM_NAME: () => LocalizedString
		/**
		 * Role name
		 */
		ROLE_NAME: () => LocalizedString
		/**
		 * Employee
		 */
		EMPLOYEE: () => LocalizedString
		/**
		 * Employee's username
		 */
		EMPLOYEE_USERNAME: () => LocalizedString
	}
	ganttView: {
		/**
		 * Tasks
		 */
		TASKS: () => LocalizedString
		/**
		 * Gantt
		 */
		GANTT: () => LocalizedString
		/**
		 * Kanban
		 */
		KANBAN: () => LocalizedString
		/**
		 * Employees
		 */
		EMPLOYEES: () => LocalizedString
		/**
		 * Budget
		 */
		BUDGET: () => LocalizedString
		/**
		 * fetching
		 */
		FETCHING: () => LocalizedString
	}
	taskView: {
		/**
		 * Created
		 */
		CREATED: () => LocalizedString
		/**
		 * Create {type}
		 */
		CREATE_OBJ: (arg: { type: string }) => LocalizedString
		/**
		 * Edit {type}
		 */
		EDIT_OBJ: (arg: { type: string }) => LocalizedString
		/**
		 * Updated
		 */
		UPDATED: () => LocalizedString
		/**
		 * Task deleted
		 */
		TASK_DELETED: () => LocalizedString
		/**
		 * Add New Activity
		 */
		ADD_NEW_ACTIVITY: () => LocalizedString
		/**
		 * Add New Task
		 */
		ADD_NEW_TASK: () => LocalizedString
		/**
		 * Delete task
		 */
		DELETE_TASK: () => LocalizedString
		/**
		 * Task
		 */
		TASK: () => LocalizedString
		/**
		 * Activity
		 */
		ACTIVITY: () => LocalizedString
	}
	kanban: {
		/**
		 * Delete state "{name}"
		 */
		DELETE_STATE: (arg: { name: string }) => LocalizedString
		/**
		 * State name
		 */
		STATE_NAME: () => LocalizedString
	}
	sidebar: {
		/**
		 * Enter to edit name
		 */
		ENTER_TO_EDIT: () => LocalizedString
		/**
		 * State
		 */
		STATE: () => LocalizedString
		/**
		 * Actual Start date
		 */
		ACTUAL_START_DATE: () => LocalizedString
		/**
		 * Actual end date
		 */
		ACTUAL_END_DATE: () => LocalizedString
		/**
		 * Planned Start Date
		 */
		PLANNED_START_DATE: () => LocalizedString
		/**
		 * Planned End Date
		 */
		PLANNED_END_DATE: () => LocalizedString
		/**
		 * Start Date
		 */
		START_DATE: () => LocalizedString
		/**
		 * End Date
		 */
		END_DATE: () => LocalizedString
		/**
		 * Planned Budget
		 */
		PLANNED_BUDGET: () => LocalizedString
		/**
		 * Budget
		 */
		BUDGET: () => LocalizedString
		/**
		 * Assignee
		 */
		ASSIGNEE: () => LocalizedString
		/**
		 * Employee name
		 */
		EMPLOYEE_NAME: () => LocalizedString
		/**
		 * Not assigned
		 */
		NOT_ASSIGNED: () => LocalizedString
		/**
		 * Comments
		 */
		COMMENTS: () => LocalizedString
		/**
		 * Write your message!
		 */
		WRITE_YOUR_MESSAGE: () => LocalizedString
		/**
		 * Send
		 */
		SEND: () => LocalizedString
	}
	assignedToMe: {
		/**
		 * {d|shortDate}
		 */
		DATE: (arg: { d: unknown }) => LocalizedString
	}
	navigationSidebar: {
		/**
		 * Sidebar
		 */
		SIDEBAR: () => LocalizedString
		/**
		 * Projects
		 */
		PROJECTS: () => LocalizedString
		/**
		 * Assigned
		 */
		ASSIGNED: () => LocalizedString
		/**
		 * Log out
		 */
		LOG_OUT: () => LocalizedString
	}
	mainTopbar: {
		/**
		 * Search here...
		 */
		SEARCH_HERE: () => LocalizedString
	}
	gantt: {
		/**
		 * Name
		 */
		NAME: () => LocalizedString
		/**
		 * From
		 */
		FROM: () => LocalizedString
		/**
		 * To
		 */
		TO: () => LocalizedString
		/**
		 * EarlyStart
		 */
		EARLYSTART: () => LocalizedString
		/**
		 * EarlyFinal
		 */
		EARLYFINAL: () => LocalizedString
		/**
		 * LatelyStart
		 */
		LATELYSTART: () => LocalizedString
		/**
		 * LatelyFinal
		 */
		LATELYFINAL: () => LocalizedString
		/**
		 * {d|tooltipDate}
		 */
		DATE: (arg: { d: number }) => LocalizedString
	}
}

export type Formatters = {
	dateFormatter: (value: string) => unknown
	shortDate: (value: unknown) => unknown
	tooltipDate: (value: number) => unknown
}
